heat_template_version: 2015-04-30

description: Template to create 2 VMs

parameters:
  image_name_1: 
    type: string 
    label: Fedora-Cloud-Base-30-1.2.x86_64 
    description: Fedora image
    default: Fedora-Cloud-Base-30-1.2.x86_64
  image_name_2: 
    type: string 
    label: cirros-0.4.0-x86_64-disk
    description: Cirros image 
    default: cirros-0.4.0-x86_64-disk
  network_id:
    type: string
    label: Network ID
    description: server-network

resources: 
  my_instance1: 
    type: OS::Nova::Server 
    properties: 
      image: { get_param: image_name_1 } 
      flavor: m1.small 
      networks:
        - network : { get_param : network_id }
  my_instance2: 
    type: OS::Nova::Server 
    properties: 
      image: { get_param: image_name_2 } 
      flavor: m1.tiny
      networks:
        - network : { get_param : network_id }